[package]
name = "chriscerie/iter"
description = ""
version = "0.1.0"
license = "MIT"
authors = ["Christopher Chang"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@^0.4"
