[package]
name = "chriscerie/iter"
description = "A composable immutable table library for Lua based on Rust's iterators."
version = "0.1.4"
license = "MIT"
authors = ["Christopher Chang"]
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@^0.4"
