name: docs

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  deploy_docs:
    name: deploy_docs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install moonwave
        run: npm install moonwave

      - name: Build docs
        run: npx moonwave build

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          branch: gh-pages
          folder: build